# Generated by Django 5.2.4 on 2025-07-14 17:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lost', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lostitem',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lostitem',
            name='location',
            field=models.CharField(choices=[('Central Library', 'Central Library'), ('Bus', 'Bus'), ('Central Mosque', 'Central Mosque'), ('C building', 'C building'), ('Lab', 'Lab')], max_length=100),
        ),
    ]
